name: "Zephyr Driver CI/CD"

on: [push, workflow_dispatch]

jobs:
  zephyr-driver:
    uses: catie-aq/zephyr_workflows/.github/workflows/driver.yml@7-create-cicd-for-zephyr-driver
    secrets:
      personal_access_token: ${{ secrets.PAT }}
        